# Generated by Django 6.0.4 on 2026-04-20 01:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('SUPERADMIN', 'Super Admin'), ('GERENTE', 'Gerente'), ('COORDENADOR', 'Coordenador'), ('ANALISTA', 'Analista')], max_length=20, null=True),
        ),
    ]
