# Generated by Django 6.0.4 on 2026-04-20 02:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True, null=True)),
                ('priority_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queues', to='organizations.operation')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queues', to='organizations.team')),
            ],
            options={
                'verbose_name': 'Fila',
                'verbose_name_plural': 'Filas',
                'ordering': ['priority_order', 'name'],
                'unique_together': {('operation', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_id', models.CharField(db_index=True, max_length=100)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('info', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('IN_PROGRESS', 'Em andamento'), ('FINISHED', 'Finalizado'), ('REJECTED_OTHER', 'Rejeitado - Outros'), ('STORE_CLOSED', 'Loja fechada'), ('PENDING_INFO', 'Pendente de informação'), ('STANDBY_STORE_CLOSED', 'Standby - Loja fechada'), ('STANDBY_NEXT_DAY', 'Standby - Próximo dia'), ('REASSIGNMENT_PENDING', 'Aguardando reatribuição')], db_index=True, default='PENDING', max_length=40)),
                ('fifo_date', models.DateTimeField(db_index=True)),
                ('due_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('retry_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('justification', models.TextField(blank=True, null=True)),
                ('inherited_note', models.TextField(blank=True, null=True)),
                ('standby_reason', models.CharField(blank=True, choices=[('STORE_CLOSED', 'Loja fechada'), ('NEXT_DAY', 'Próximo dia'), ('OTHER', 'Outro')], max_length=30, null=True)),
                ('standby_note', models.TextField(blank=True, null=True)),
                ('menu_created', models.BooleanField(blank=True, null=True)),
                ('reassignment_count', models.PositiveIntegerField(default=0)),
                ('standby_count', models.PositiveIntegerField(default=0)),
                ('is_priority', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_demands', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_demands', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_demands', to=settings.AUTH_USER_MODEL)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demands', to='organizations.operation')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demands', to='organizations.organization')),
                ('return_to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_demands', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demands', to='organizations.team')),
                ('queue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demands', to='demands.queue')),
            ],
            options={
                'verbose_name': 'Demanda',
                'verbose_name_plural': 'Demandas',
                'ordering': ['fifo_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DemandAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_assignments', to=settings.AUTH_USER_MODEL)),
                ('demand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='demands.demand')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Atribuição da Demanda',
                'verbose_name_plural': 'Atribuições da Demanda',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['user', 'is_current'], name='demands_dem_user_id_daba6d_idx'), models.Index(fields=['demand', 'is_current'], name='demands_dem_demand__cf0ea5_idx')],
            },
        ),
        migrations.CreateModel(
            name='DemandHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=60)),
                ('from_status', models.CharField(blank=True, max_length=40, null=True)),
                ('to_status', models.CharField(blank=True, max_length=40, null=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demand_history_actions', to=settings.AUTH_USER_MODEL)),
                ('demand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='demands.demand')),
            ],
            options={
                'verbose_name': 'Histórico da Demanda',
                'verbose_name_plural': 'Históricos da Demanda',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='demands_dem_action_1cd56b_idx'), models.Index(fields=['actor', 'created_at'], name='demands_dem_actor_i_52f4ed_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='demand',
            index=models.Index(fields=['status', 'fifo_date'], name='demands_dem_status_56d961_idx'),
        ),
        migrations.AddIndex(
            model_name='demand',
            index=models.Index(fields=['operation', 'status'], name='demands_dem_operati_eccce3_idx'),
        ),
        migrations.AddIndex(
            model_name='demand',
            index=models.Index(fields=['team', 'status'], name='demands_dem_team_id_ef4717_idx'),
        ),
        migrations.AddIndex(
            model_name='demand',
            index=models.Index(fields=['assigned_to', 'status'], name='demands_dem_assigne_b2f59f_idx'),
        ),
        migrations.AddIndex(
            model_name='demand',
            index=models.Index(fields=['queue', 'status'], name='demands_dem_queue_i_e8cd40_idx'),
        ),
        migrations.AddIndex(
            model_name='demand',
            index=models.Index(fields=['retry_at', 'status'], name='demands_dem_retry_a_40bf3b_idx'),
        ),
        migrations.AddIndex(
            model_name='demand',
            index=models.Index(fields=['shop_id', 'status'], name='demands_dem_shop_id_da463e_idx'),
        ),
    ]
