# Generated by Django 6.0.4 on 2026-05-11 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('IN_PROGRESS', 'Em andamento'), ('INTERRUPTED', 'Interrompida'), ('FINISHED', 'Finalizado'), ('REJECTED_OTHER', 'Rejeitado - Outros'), ('STORE_CLOSED', 'Loja fechada'), ('PENDING_INFO', 'Pendente de informação'), ('STANDBY_STORE_CLOSED', 'Standby - Loja fechada'), ('STANDBY_NEXT_DAY', 'Standby - Próximo dia'), ('REASSIGNMENT_PENDING', 'Aguardando reatribuição')], db_index=True, default='PENDING', max_length=40),
        ),
    ]
