# Generated by Django 6.0.4 on 2026-05-14 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0002_alter_demand_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='active_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='demand',
            name='current_cycle_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
